# Generated by Django 5.1.5 on 2025-02-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky_api', '0001_initial'),
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StrCity',
            new_name='SubCity',
        ),
    ]
