# Generated by Django 5.1.5 on 2025-02-01 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_api', '0001_initial'),
        ('users_api', '0002_rename_strcity_subcity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcity',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_city', to='sky_api.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='subcity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
