# Generated by Django 5.1.5 on 2025-02-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0003_alter_subcity_city_alter_subcity_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCity',
        ),
    ]
