# Generated by Django 5.1.5 on 2025-01-27 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('x', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='X')),
                ('y', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Y')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Температура')),
                ('city', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sky_api.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Прогноз',
                'verbose_name_plural': 'Города',
            },
        ),
    ]
