# Generated by Django 5.1.5 on 2025-01-30 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='широта')),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='высота')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время')),
                ('temp', models.SmallIntegerField(default=0, verbose_name='Температура')),
                ('humidity', models.SmallIntegerField(default=0, verbose_name='`Влажность`')),
                ('precipitation', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Осадки')),
                ('wind', models.SmallIntegerField(default=0, verbose_name='Скорость ветра')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sky_api.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Погода',
                'verbose_name_plural': 'Погода',
            },
        ),
    ]
