# Generated by Django 5.1.5 on 2025-01-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temp',
            options={'verbose_name': 'Погода', 'verbose_name_plural': 'Погода'},
        ),
        migrations.RemoveField(
            model_name='city',
            name='x',
        ),
        migrations.RemoveField(
            model_name='city',
            name='y',
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='широта'),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='высота'),
        ),
        migrations.AddField(
            model_name='temp',
            name='press',
            field=models.SmallIntegerField(default=0, verbose_name='Давление'),
        ),
        migrations.AddField(
            model_name='temp',
            name='wind',
            field=models.SmallIntegerField(default=0, verbose_name='Скорость ветра'),
        ),
        migrations.AlterField(
            model_name='temp',
            name='temp',
            field=models.SmallIntegerField(default=0, verbose_name='Температура'),
        ),
    ]
