# Generated by Django 5.1.5 on 2025-01-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_api', '0002_alter_temp_options_remove_city_x_remove_city_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
