# Generated by Django 5.1.5 on 2025-02-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_api', '0002_city_owner_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='широта'),
        ),
    ]
