# Generated by Django 5.1.5 on 2025-01-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_api', '0003_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
