# Generated by Django 5.1.5 on 2025-02-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_api', '0004_alter_temp_humidity_alter_temp_precipitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='precipitation',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Осадки'),
        ),
    ]
