# Generated by Django 5.1.5 on 2025-01-29 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_api', '0005_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sky_api.city', verbose_name='Город'),
        ),
    ]
