# Generated by Django 5.1.5 on 2025-01-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_api', '0007_alter_city_name_alter_temp_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='press',
        ),
        migrations.AddField(
            model_name='temp',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время'),
        ),
        migrations.AddField(
            model_name='temp',
            name='humidity',
            field=models.SmallIntegerField(default=0, verbose_name='`Влажность`'),
        ),
        migrations.AddField(
            model_name='temp',
            name='precipitation',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Осадки'),
        ),
    ]
